---
name: Unit Tests and Linting for Service Package "apimanagement"
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - 'internal/services/apimanagement/**'

concurrency:
  group: 'unit-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: bash scripts/service-package.sh "apimanagement"
