---
name: Unit Tests and Linting for New Service Packages
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - 'internal/services/**'
      - '!internal/services/aadb2c/**'
      - '!internal/services/advisor/**'
      - '!internal/services/analysisservices/**'
      - '!internal/services/apimanagement/**'
      - '!internal/services/appconfiguration/**'
      - '!internal/services/applicationinsights/**'
      - '!internal/services/appservice/**'
      - '!internal/services/attestation/**'
      - '!internal/services/authorization/**'
      - '!internal/services/automation/**'
      - '!internal/services/azurestackhci/**'
      - '!internal/services/batch/**'
      - '!internal/services/billing/**'
      - '!internal/services/blueprints/**'
      - '!internal/services/bot/**'
      - '!internal/services/cdn/**'
      - '!internal/services/cognitive/**'
      - '!internal/services/communication/**'
      - '!internal/services/compute/**'
      - '!internal/services/consumption/**'
      - '!internal/services/containers/**'
      - '!internal/services/cosmos/**'
      - '!internal/services/costmanagement/**'
      - '!internal/services/customproviders/**'
      - '!internal/services/databasemigration/**'
      - '!internal/services/databoxedge/**'
      - '!internal/services/databricks/**'
      - '!internal/services/datafactory/**'
      - '!internal/services/datalake/**'
      - '!internal/services/dataprotection/**'
      - '!internal/services/datashare/**'
      - '!internal/services/desktopvirtualization/**'
      - '!internal/services/devspace/**'
      - '!internal/services/devtestlabs/**'
      - '!internal/services/digitaltwins/**'
      - '!internal/services/disks/**'
      - '!internal/services/dns/**'
      - '!internal/services/domainservices/**'
      - '!internal/services/eventgrid/**'
      - '!internal/services/eventhub/**'
      - '!internal/services/firewall/**'
      - '!internal/services/frontdoor/**'
      - '!internal/services/hdinsight/**'
      - '!internal/services/healthcare/**'
      - '!internal/services/hpccache/**'
      - '!internal/services/hsm/**'
      - '!internal/services/iotcentral/**'
      - '!internal/services/iothub/**'
      - '!internal/services/iottimeseriesinsights/**'
      - '!internal/services/keyvault/**'
      - '!internal/services/kusto/**'
      - '!internal/services/lighthouse/**'
      - '!internal/services/loadbalancer/**'
      - '!internal/services/loganalytics/**'
      - '!internal/services/logic/**'
      - '!internal/services/logz/**'
      - '!internal/services/machinelearning/**'
      - '!internal/services/maintenance/**'
      - '!internal/services/managedapplications/**'
      - '!internal/services/managementgroup/**'
      - '!internal/services/maps/**'
      - '!internal/services/mariadb/**'
      - '!internal/services/media/**'
      - '!internal/services/mixedreality/**'
      - '!internal/services/monitor/**'
      - '!internal/services/msi/**'
      - '!internal/services/mssql/**'
      - '!internal/services/mysql/**'
      - '!internal/services/netapp/**'
      - '!internal/services/network/**'
      - '!internal/services/notificationhub/**'
      - '!internal/services/policy/**'
      - '!internal/services/portal/**'
      - '!internal/services/postgres/**'
      - '!internal/services/powerbi/**'
      - '!internal/services/privatedns/**'
      - '!internal/services/purview/**'
      - '!internal/services/recoveryservices/**'
      - '!internal/services/redis/**'
      - '!internal/services/redisenterprise/**'
      - '!internal/services/relay/**'
      - '!internal/services/resource/**'
      - '!internal/services/search/**'
      - '!internal/services/securitycenter/**'
      - '!internal/services/sentinel/**'
      - '!internal/services/servicebus/**'
      - '!internal/services/servicefabric/**'
      - '!internal/services/servicefabricmanaged/**'
      - '!internal/services/servicefabricmesh/**'
      - '!internal/services/signalr/**'
      - '!internal/services/springcloud/**'
      - '!internal/services/sql/**'
      - '!internal/services/storage/**'
      - '!internal/services/streamanalytics/**'
      - '!internal/services/subscription/**'
      - '!internal/services/synapse/**'
      - '!internal/services/trafficmanager/**'
      - '!internal/services/videoanalyzer/**'
      - '!internal/services/vmware/**'
      - '!internal/services/web/**'

concurrency:
  group: 'unit-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
      - run: bash scripts/gogetcookie.sh
      - run: bash scripts/run-new-service-packages.sh
